# Generated by Django 5.0.6 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_start_t_0f9aa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_room_idx',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time', 'end_time', 'room'], name='core_lesson_start_t_0f9aa2_idx'),
        ),
    ]
