# Generated by Django 5.0.6 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lesson_core_lesson_start_t_0f9aa2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_start_t_0f9aa2_idx',
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time', 'end_time'], name='core_lesson_start_t_f3a87c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room'], name='core_lesson_room_id_395ed3_idx'),
        ),
    ]
