# Generated by Django 5.0.6 on 2025-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lesson_core_lesson_start_t_0f9aa2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.discipline', verbose_name='Дисциплины'),
        ),
    ]
