# Generated by Django 5.0.6 on 2025-12-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='disciplines',
        ),
    ]
