# Generated by Django 4.2.26 on 2025-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacher_disciplines'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='core_lesson_week_0df2ce_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='week',
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group'], name='core_lesson_group_i_4da07f_idx'),
        ),
    ]
