# Generated by Django 4.2.26 on 2025-12-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_lesson_core_lesson_week_0df2ce_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['week'], name='core_lesson_week_88f7e3_idx'),
        ),
    ]
